### ISSUE TITLE
Testing Framework: Implement Test for enable-arch-multilib-repo Configuration

### ISSUE THREAD

**Issue by zipproth** [acrion/ditana-installer#9]
# Context

As part of improving the robustness of Ditana Installer, we need to implement automated tests that run before ISO generation. These tests will validate the functionality of various configuration procedures used in the installation process. This is especially important as we're planning to port the Ansible playbooks to Sparrow6 (https://github.com/melezhik/Sparrow6). Having tests in place will:

1. Ensure the current functionality works correctly
2. Facilitate a smooth, incremental migration to Sparrow6
3. Verify functionality throughout the transition process

# Specific Task

This issue addresses the first test implementation for the configuration procedure currently implemented in:
https://github.com/acrion/ditana-installer/blob/main/airootfs/root/bind-mount/root/enable-arch-multilib-repo.yaml

Currently, this procedure is executed with:
```bash
ansible-playbook -i localhost, enable-arch-multilib-repo.yaml -e "enable_multilib=$ENABLE_MULTILIB"
```

The test implementation needs to be written in Raku, as Sparrow6 validation will be used in the future. The main directory for this task should be a new directory `/tests/configuration`.

# Playbook Modification

The current playbook has a hardcoded path to `/etc/pacman.conf`. I've modified it to accept an optional parameter:

```yaml
---
- hosts: localhost
  connection: local
  vars:
    config_path: "{{ pacman_conf_path | default('/etc/pacman.conf') }}"
  tasks:
  - name: Enable Arch multilib repo if enable_multilib is y
    replace:
      path: "{{ config_path }}"
      regexp: '^\s*#?\s*\[multilib\]\s*\n\s*#?\s*Include\s*=\s*/etc/pacman.d/mirrorlist'
      replace: '\n[multilib]\nInclude = /etc/pacman.d/mirrorlist'
    when: enable_multilib == "y"
```

With this modification, the playbook can be executed with:
```bash
# Default behavior (uses /etc/pacman.conf)
ansible-playbook -i localhost, enable-arch-multilib-repo.yaml -e "enable_multilib=$ENABLE_MULTILIB"

# For testing (uses a specified path)
ansible-playbook -i localhost, enable-arch-multilib-repo.yaml -e "enable_multilib=$ENABLE_MULTILIB pacman_conf_path=/tmp/test-pacman.conf"
```

# Test Requirements

Implement a test framework that:

1. Copies test files to a temporary location before testing
2. Runs the playbook against these temporary files
3. Validates that the configuration is correctly modified

## Test File Preparation

The test should:
1. Create a temporary directory
2. Copy the test configuration files to this temporary directory
3. Run the playbook targeting these copied files
4. Validate the results
5. Clean up the temporary directory

## Test Files

Create the following test configurations in the test directory:

### Test Files
- Test file 1: Commented multilib lines (please make a copy of [pacman.conf](https://github.com/acrion/ditana-installer/blob/main/pacman.conf) and comment the two lines)
```
#[multilib]
#Include = /etc/pacman.d/mirrorlist
```
- Test file 2: Missing multilib lines (please make a copy of [pacman.conf](https://github.com/acrion/ditana-installer/blob/main/pacman.conf) and delete the two lines)
- Test file 3: Active multilib lines (please make a copy of [pacman.conf](https://github.com/acrion/ditana-installer/blob/main/pacman.conf))
```
[multilib]
Include = /etc/pacman.d/mirrorlist
```

### Test Scenarios
1. Copy Test file 1 to temp location → Run with `enable_multilib=y` → should uncomment lines
2. Copy Test file 1 to temp location → Run with `enable_multilib=n` → should leave lines commented
3. Copy Test file 2 to temp location → Run with `enable_multilib=y` → should fail
4. Copy Test file 2 to temp location → Run with `enable_multilib=n` → should fail
5. Copy Test file 3 to temp location → Run with `enable_multilib=y` → should leave lines uncommented
6. Copy Test file 3 to temp location → Run with `enable_multilib=n` → should comment lines

# Validation with Sparrow6

After the playbook execution, Sparrow6 should validate whether the file was correctly modified based on the given parameters. The test should verify:

- When `enable_multilib` is set to `y`, commented multilib lines should be uncommented
- When `enable_multilib` is set to `n`, the multilib configuration should remain commented or be left unchanged
- When the lines in the test file are missing, the modification must have failed

# Notes
- With the current version of the playbook, test scenario (6) should fail and the other 5 should succeed.
- This is the first of several similar tests to be implemented
- This approach will serve as a template for testing other configuration procedures

**Comment by melezhik** [comment]
I guess we can ( in  a future replace ansible replacement by Sparrow replacement ) - https://github.com/melezhik/Sparrow6/blob/master/documentation/taskchecks.md#replace

E.g.

```yaml

 - name: Check if "keyboard" is in mkinitcpio HOOKS
      command: grep "^HOOKS=.*\bkeyboard\b" /etc/mkinitcpio.conf
      register: keyboard_check
      failed_when: keyboard_check.rc > 1
      changed_when: false

  - name: For LUKS encryption on all init systems, add keyboard hook after kms hook
      replace:
        path: /etc/mkinitcpio.conf
        regexp: '\bkms\b'
        replace: 'kms keyboard'
      when:
        - encrypt_root_partition == "y"
        - zfs_filesystem != "y"
        - keyboard_check.rc != 0
```

would be something:

```
# set search context to HOOKS= none empty string
# so that all subsequent searches will be inside HOOKS= string

within: ^^ "HOOKS="   \s* \S

# check if kms is set
~regexp: \bkms\b

code: <<RAKU

if matched() {
  say "kms is set";
  my $s = get_state(); $s<has_kms> = True; update_state($s);   
}
RAKU

# check if keyboard is set 

~regexp: \bkeyboard\b

code: <<RAKU

if matched() {
  say "keyboard is set";
  my $s = get_state(); $s<has_keyboard> = True; update_state($s)   
}
RAKU

# check if we find any none empty string in HOOKS=
regexp: :any:

code: <<RAKU
# only replace if previous regexp succeeds
# in other words if HOOKS are not empty 
if  my $updated-line = matched() {
    my $s = get_state();
    my $ln = captures-full()[0]<index>; # line numer of the file where to replace

    if $s<has_kms> && ( $s<has_keyboard> || config()<zfs_filesystem> || config()<encrypt_root_partition>) {
       $updated-line.=subst(/\bkms\b/,"kms keyboard") 
    }
    # finaly update mkinitcpio.conf
    replace("/etc/mkinitcpio.conf",$ln,$updated-line);
}
RAKU
```

This seems a bit more of code, but this is also more acurate, for example current ansible version does not check for HOOKS= context when replace \bkms\b chunk of string, so this might be faulty if we say have "standalone"  \bkms\b strings (not part of HOOKS= string)
